p8105_hw6_xk2163
================
Kang
2024-12-03

``` r
library(tidyverse)
library(ggplot2)
```

# Problem 2

``` r
data_df = 
  read_csv("Data/homicide-data.csv") |> 
  janitor::clean_names() |> 
  mutate(city_state = paste(city,state, sep = ", "),
         resolved = case_when(
           disposition == "Closed by arrest" ~ 1,
           disposition == "Closed without arrest" ~ 1,
           disposition == "Open/No arrest" ~ 0),
         victim_age = as.numeric(victim_age)) |> 
  filter(!(city %in% 
             c("Dallas", "Phoenix", "Kansas City", "Tulsa")) & 
           (victim_race == "Black" | victim_race == "White")) 
```

    ## Rows: 52179 Columns: 12
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (9): uid, victim_last, victim_first, victim_race, victim_age, victim_sex...
    ## dbl (3): reported_date, lat, lon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In the above part, I create a new `city_state` variable by combining the
city and state names. Then, I generate a binary `resolved` variable,
where homicides marked as “Closed by arrest” or “Closed without arrest”
are coded as 1 (resolved), and “Open/No arrest” cases are coded as 0
(unresolved). I also convert the `victim_age` column to a numeric type
for further analysis. Lastly, I filter out records from specific cities
(Dallas, Phoenix, Kansas City, and Tulsa) due to incomplete race data,
and limit the data to cases where the victim’s race is either Black or
White.

``` r
data_balti = data_df |> 
  filter(city_state == "Baltimore, MD")

baltimore_model =
  glm(
    resolved ~ victim_age + victim_sex + victim_race,
    data = data_balti,
    family = binomial)

broom::tidy(baltimore_model) |> 
  mutate(odds_ratio = exp(estimate),   
         conf.low = exp(estimate - 1.96 * std.error),   
         conf.high = exp(estimate + 1.96 * std.error)) |> 
  select(term, estimate, odds_ratio, conf.low, conf.high, p.value) |>
  knitr::kable(
    caption = "Logistic Regression Results for Solving Homicides in Baltimore, MD",
    col.names = c("Term", "Estimate", "Odds Ratio", "Conf. Low", "Conf. High", "P-value"),
    digits = 3)
```

| Term             | Estimate | Odds Ratio | Conf. Low | Conf. High | P-value |
|:-----------------|---------:|-----------:|----------:|-----------:|--------:|
| (Intercept)      |    0.664 |      1.942 |     1.380 |      2.734 |    0.00 |
| victim_age       |   -0.005 |      0.995 |     0.988 |      1.001 |    0.11 |
| victim_sexMale   |   -1.037 |      0.355 |     0.268 |      0.469 |    0.00 |
| victim_raceWhite |    0.900 |      2.459 |     1.727 |      3.501 |    0.00 |

Logistic Regression Results for Solving Homicides in Baltimore, MD

Then, I fit a logistic regression model to predict whether a homicide
case is resolved in `Baltimore`, using the victim’s age, sex, and race
as predictors. After fitting the model, I used `broom::tidy` to organize
the model output and calculated the odds ratios and their 95% confidence
intervals for each predictor by exponentiating the coefficient estimates
and confidence bounds. Finally, I formatted the table to display the
term, estimate, odds ratio, confidence intervals, and p-values.

### Explanation of Results:

- **Intercept**: The baseline odds of a case being resolved when all
  predictors are at their reference levels. The odds ratio is 1.942,
  indicating that, on average, cases have nearly twice the odds of being
  resolved at the baseline level.
- **victim_age**: The odds ratio of 0.995 suggests that each additional
  year of age slightly decreases the odds of resolution, though this
  effect is not statistically significant (p = 0.11).
- **victim_sexMale**: The odds ratio of 0.355 indicates that cases
  involving male victims have significantly lower odds (around 64.5%
  lower) of being resolved compared to female victims, with a p-value of
  0.00.
- **victim_raceWhite**: The odds ratio of 2.459 implies that cases
  involving White victims have significantly higher odds of being
  resolved (about 146% higher) than cases with Black victims, with a
  p-value of 0.00.

These results highlight significant differences in the resolution rates
of homicides based on victim characteristics, particularly victim sex
and race.
